### ISSUE TITLE
Not handling URL 302 redirection properly

### ISSUE THREAD

**Issue by LoveMyData** [monkeysuffrage/pgbrowser#5]
Use pgBrowser to get  http://eplanning.parracity.nsw.gov.au/Pages/XC.Track/SearchApplication.aspx
HTTP 302 redirected to http://eplanning.parracity.nsw.gov.au/Common/Common/Terms.aspx

Then use pgBrowser to submit
pgBrowser submitted to http://eplanning.parracity.nsw.gov.au/Pages/XC.Track/Terms.aspx but it should be http://eplanning.parracity.nsw.gov.au/Common/Common/Terms.aspx

Form action only specify 'Terms.aspx'

**Comment by monkeysuffrage** [comment]
Yes I can see why that would happen. For a workaround you can set
$form->action yourself.

**Comment by LoveMyData** [comment]
I have made a PR with the fix and I am hoping you can have a look and see is it any good to you.

**Comment by monkeysuffrage** [comment]
Thanks Eric!

**Comment by LoveMyData** [comment]
Thanks for accepting the code
